article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    # path('', views.Homepage, name='homepage'),
    path('article_list/', views.aricle_list, name='article_list'),
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_safe_delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article_update/<int:id>/', views.article_update, name='article_update'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [

    path('article', include('article.urls', namespace='article')),
    path('admin/', admin.site.urls),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('password_reset/', include('password_reset.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('', include('news.urls', namespace='news')),
]

#为上传图片配置url路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.Homepage, name='homepage'),
    path('news_list/', views.news_list, name='news_list'),
    path('news_detail/<int:id>/', views.news_detail, name='news_detail'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_register, name='signup'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load staticfiles %}
<!--<!DOCTYPE html>-->
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.bootcss.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/4.3.1/css/blog.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/4.3.1/css/grid.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/4.3.1/css/navbars.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/bootstrap/4.3.1/css/carousel.css" rel="stylesheet">
    <link href="{% static 'md_css/monokai.css' %}" rel="stylesheet">
    <!--矢量图标-->
    <link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    >
</head>

<body>
    {% include 'header.html' %}
    <div id="wrapper">
        {% block content %} {% endblock content %}
        <div id="push"></div>
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.4.1.js' %"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    {% block script %}{% endblock script %}
    {% include 'back_to_top_func.html' %}

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }
        #footer,
        #push {
            height: 60px;
        }
    </style>

</body>
</html>

templates/footer.html
{% load staticfiles %}
<footer id="footer" class="blog-footer">
  <p>Bruce Wang's Blog | template built for
    <a href="https://getbootstrap.com/">Bootstrap</a> by
    <a href="https://twitter.com/mdo">@mdo</a> |
    Copyright@2020
    <br/>
    <a href="#">Back to top</a>
  </p>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'news:homepage' %}">首页</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:news_list' %}">要闻</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:news_list' %}">国际</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:news_list' %}">国内</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:news_list' %}">科技</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'news:news_list' %}">军事</a>
        </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:article_list' %}">文章列表</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:article_create' %}">发表文章</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-md-0">
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
<!--                <a class="btn btn-outline-success mr-sm-2" href="#">{{ user.username }}</a>-->
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <!-- 消息通知,小红点 -->
                    {% if unread_count %}
                        <svg viewBox="0 0 8 8" width="8px" height="8px">
                            <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                        </svg>
                    {% endif %}
                    {{ user.username }}
                </a>
                <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                    <!-- 通知计数 -->
                    <a class="dropdown-item" href="{% url 'notice:list' %}">通知
                        {% if unread_count %}
                        <span class="badge badge-danger">{{ unread_count }}</span>
                        {% endif %}
                    </a>
                    <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
<!--                    <a class="dropdown-item btn-sm" href="{% url 'userprofile:logout' %}">退出登录</a>-->
<!--                    <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>-->

                    <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                </div>
                <a class="btn-sm" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
            </li>
        {% else %}
            <a class="btn btn-outline-success mr-sm-2" href="{% url 'userprofile:login' %}">登录</a>
        {% endif %}
        <a class="btn btn-outline-success mr-sm-2" href="{% url 'userprofile:signup' %}">注册</a>
        <input class="form-control mr-sm-2" type="text" placeholder="搜索" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
    </form>
  </div>
</nav>

{% if user.is_authenticated %}
    <form
        style="display:none;"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="POST"
    >
    {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}

templates/myblog.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}


<div class="container">

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">


      <div class="blog-post">
        <h2 class="blog-post-title">first blog</h2>
        <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>
        <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
        <hr>
      </div>


      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
      </nav>

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main><!-- /.container -->

{% endblock content %}